<a href="https://colab.research.google.com/github/akshara-git17/synent-task8-customer-segmentation-akshara_dave/blob/main/Task8_Customer_Segmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Customer Segmentation using K-Means Clustering

## Synent Technologies Data Science Internship

### Submitted By:
Akshara Dave

### Objective

The objective of this project is to segment customers into distinct groups based on their income and spending behavior using K-Means Clustering. Customer segmentation helps businesses understand customer patterns and develop targeted marketing strategies.

# Business Objective

Businesses often have customers with different purchasing behaviors. Treating all customers the same can reduce the effectiveness of marketing efforts.

The goal of this project is to:

- Identify distinct customer groups.
- Understand customer spending behavior.
- Support targeted marketing strategies.
- Improve customer relationship management.
- Assist business decision-making using machine learning techniques.

In [1]:
#importing libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

pd.set_option('display.max_columns', None)

In [2]:
#load dataset
df = pd.read_csv('Mall_Customers.csv')

df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

# Dataset Overview

Before building the clustering model, it is important to understand the dataset structure, data types, and available features.

In [3]:
df.shape

(200, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [5]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [6]:
#checking for missing values
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [7]:
#checking for duplicates
df.duplicated().sum()

np.int64(0)